# Generated by Django 6.0.1 on 2026-02-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id_chat_tg",
            field=models.CharField(
                help_text="Укажите ID чата в telegram",
                verbose_name="ID чата в telegram",
            ),
        ),
    ]
