# Generated by Django 6.0.1 on 2026-02-02 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=120)),
                ("time", models.DateTimeField()),
                ("action", models.CharField(max_length=120)),
                ("is_pleasant", models.BooleanField()),
                ("periodicity", models.PositiveIntegerField(default=1)),
                ("award", models.TextField(blank=True, null=True)),
                ("time_to_complete", models.PositiveIntegerField()),
                ("is_public", models.BooleanField(default=True)),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="habit_tracker.habit",
                    ),
                ),
            ],
        ),
    ]
