# Generated by Django 6.0.1 on 2026-02-04 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit_tracker", "0004_alter_habit_periodicity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MaxValueValidator(7)]
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time_to_complete",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MaxValueValidator(120)]
            ),
        ),
    ]
