# Generated by Django 6.0.1 on 2026-02-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit_tracker", "0005_alter_habit_periodicity_alter_habit_time_to_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default="2026-02-11"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(),
        ),
    ]
