# Generated by Django 6.0.1 on 2026-02-11 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habit_tracker", "0006_habit_created_at_alter_habit_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="habit",
            old_name="created_at",
            new_name="last_reminder_date",
        ),
    ]
