# Generated by Django 6.0.1 on 2026-02-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit_tracker", "0007_rename_created_at_habit_last_reminder_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="created_at",
            field=models.DateField(auto_now_add=True, default="2026-02-11"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="habit",
            name="last_reminder_date",
            field=models.DateField(default=None),
        ),
    ]
