# Generated by Django 6.0.1 on 2026-02-12 16:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit_tracker", "0008_habit_created_at_alter_habit_last_reminder_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="action",
            field=models.CharField(
                help_text="Укажите действие, которое выполняется в качестве привычки",
                max_length=120,
                verbose_name="Действие",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="award",
            field=models.TextField(
                blank=True,
                help_text="Укажите вознаграждение",
                null=True,
                verbose_name="Вознаграждение",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="created_at",
            field=models.DateField(
                auto_now_add=True, verbose_name="Дата создания привычки"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_pleasant",
            field=models.BooleanField(
                help_text="Признак приятной привычки",
                verbose_name="Укажите признак приятной привычки",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_public",
            field=models.BooleanField(
                default=True,
                help_text="Укажите признак публичной привычки",
                verbose_name="Признак публичной привычки",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="last_reminder_date",
            field=models.DateField(
                default=None, verbose_name="Дата последнего напоминания"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Укажите периодичность выполнения привычки",
                validators=[django.core.validators.MaxValueValidator(7)],
                verbose_name="Периодичность",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="place",
            field=models.CharField(
                help_text="Укажите место выполнения привычки",
                max_length=120,
                verbose_name="Место выполнения привычки",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                help_text="Связанная привычка",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="habit_tracker.habit",
                verbose_name="Укажите связанную привычку",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(
                help_text="Время выполнения привычки",
                verbose_name="Укажите время, в которое будет выполняться привычка",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time_to_complete",
            field=models.PositiveIntegerField(
                help_text="Укажите время выполнения привычки",
                validators=[django.core.validators.MaxValueValidator(120)],
                verbose_name="Время выполнения привычки",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
