# Generated by Django 6.0.1 on 2026-02-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit_tracker", "0009_alter_habit_action_alter_habit_award_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(
                help_text="Укажите время, в которое будет выполняться привычка",
                verbose_name="Время выполнения привычки",
            ),
        ),
    ]
