# Generated by Django 6.0.1 on 2026-02-12 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit_tracker", "0010_alter_habit_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="is_pleasant",
            field=models.BooleanField(
                help_text="Укажите признак приятной привычки",
                verbose_name="Признак приятной привычки",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите связанную привычку",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="habit_tracker.habit",
                verbose_name="Связанная привычка",
            ),
        ),
    ]
