# Generated by Django 6.0.1 on 2026-02-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit_tracker", "0011_alter_habit_is_pleasant_alter_habit_related_habit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="is_pleasant",
            field=models.BooleanField(
                default=False,
                help_text="Укажите признак приятной привычки",
                verbose_name="Признак приятной привычки",
            ),
        ),
    ]
