# Generated by Django 6.0.1 on 2026-02-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit_tracker", "0012_alter_habit_is_pleasant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="last_reminder_date",
            field=models.DateField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Дата последнего напоминания",
            ),
        ),
    ]
