# Generated by Django 6.0.1 on 2026-02-14 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit_tracker", "0014_alter_habit_periodicity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Укажите периодичность выполнения привычки",
                validators=[django.core.validators.MaxValueValidator(7)],
                verbose_name="Периодичность",
            ),
        ),
    ]
